 CREATE PROCEDURE Yammer_YearDownloadRequest (@ProcessedBy NVARCHAR(100))
 AS
 BEGIN
	 IF(((SELECT COUNT(ID) FROM YM_YAMMERYEARS WHERE ISNULL(processedBy,'') = @ProcessedBy) = 0) OR ((SELECT COUNT(1) FROM YM_YAMMERYEARS WHERE PROCESSEDBY = @ProcessedBy AND ToDownload = 1) = 0))
	 BEGIN	
		UPDATE YM_YAMMERYEARS SET PROCESSEDBY = @ProcessedBy WHERE YMYEAR = (SELECT TOP 1 YMYEAR FROM YM_YAMMERYEARS WHERE
		PROCESSEDBY IS NULL AND ToDownload = 1 AND ToRun = 1 ORDER BY sequence)
		SELECT YMYEAR FROM YM_YAMMERYEARS WHERE PROCESSEDBY = @ProcessedBy AND ToDownload = 1
	 END
	 ELSE
	 BEGIN
		SELECT YMYEAR FROM YM_YAMMERYEARS WHERE PROCESSEDBY = @ProcessedBy AND ToDownload = 1
	 END
END
