//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YammerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class dupthreads_doclibthreaddetails_20180502
    {
        public string DocLibName { get; set; }
        public string TopLevelFolderSP { get; set; }
        public string ThreadID { get; set; }
        public string ThreadID_FileName { get; set; }
        public Nullable<long> ThreadID_Size { get; set; }
        public Nullable<System.DateTime> ThreadID_CreatedDate { get; set; }
        public string ThreadID_Path { get; set; }
        public Nullable<bool> TobeDeleted { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public int ID { get; set; }
        public string ProcessedBy { get; set; }
    }
}
