//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YammerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class DupThreads_TopLevelFolderStatus
    {
        public string DocLibName { get; set; }
        public string TopLevelFolderSP { get; set; }
        public string ProcessStage { get; set; }
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
    }
}
