//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YammerLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Data.Entity.Core.EntityClient;

    public partial class YETIDBEntities : DbContext
    {
        private EntityConnection yeticon;

        public YETIDBEntities()
            : base("name=YETIDBEntities")
        {
        }
        public YETIDBEntities(string connectionString) : base(connectionString)
        {

        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ym_yammeryears> ym_yammeryears { get; set; }
        public virtual DbSet<batchnotmp> batchnotmps { get; set; }
        public virtual DbSet<Dupthreads_DocLibThreadDetails> Dupthreads_DocLibThreadDetails { get; set; }
        public virtual DbSet<dupthreads_doclibthreaddetails_20180502> dupthreads_doclibthreaddetails_20180502 { get; set; }
        public virtual DbSet<dupthreads_doclibthreaddetails_518> dupthreads_doclibthreaddetails_518 { get; set; }
        public virtual DbSet<dupthreads_doclibThreaddetails_backup> dupthreads_doclibThreaddetails_backup { get; set; }
        public virtual DbSet<DupThreads_TopLevelFolderStatus> DupThreads_TopLevelFolderStatus { get; set; }
        public virtual DbSet<spbatchlistbak> spbatchlistbaks { get; set; }
        public virtual DbSet<tempAzure> tempAzures { get; set; }
        public virtual DbSet<YM_ArchivedThreads> YM_ArchivedThreads { get; set; }
        public virtual DbSet<YM_ArchivedThreadsBak> YM_ArchivedThreadsBak { get; set; }
        public virtual DbSet<YM_ArchivedThreadsBuffer> YM_ArchivedThreadsBuffer { get; set; }
        public virtual DbSet<YM_ArchivedThreadsRepo> YM_ArchivedThreadsRepo { get; set; }
        public virtual DbSet<YM_AzureContainer> YM_AzureContainer { get; set; }
        public virtual DbSet<YM_DocumentLibraries> YM_DocumentLibraries { get; set; }
        public virtual DbSet<YM_EventLogs> YM_EventLogs { get; set; }
        public virtual DbSet<YM_EventLogs_Bak> YM_EventLogs_Bak { get; set; }
        public virtual DbSet<YM_EventLogs_bak180307> YM_EventLogs_bak180307 { get; set; }
        public virtual DbSet<YM_ExportDetails> YM_ExportDetails { get; set; }
        public virtual DbSet<YM_FileShareLists> YM_FileShareLists { get; set; }
        public virtual DbSet<YM_FileShareLsts_bak20180220> YM_FileShareLsts_bak20180220 { get; set; }
        public virtual DbSet<YM_FileThreadList> YM_FileThreadList { get; set; }
        public virtual DbSet<YM_MissedFileAttachments> YM_MissedFileAttachments { get; set; }
        public virtual DbSet<YM_MissedPageAttachments> YM_MissedPageAttachments { get; set; }
        public virtual DbSet<YM_PageThreadList> YM_PageThreadList { get; set; }
        public virtual DbSet<YM_SPBatchLists> YM_SPBatchLists { get; set; }
        public virtual DbSet<YM_SPDirectoryMapping> YM_SPDirectoryMapping { get; set; }
        public virtual DbSet<V_SPThreadDetails> V_SPThreadDetails { get; set; }
    
        public virtual int DupThreads_CheckDeleteThreadStatus(string docLibName)
        {
            var docLibNameParameter = docLibName != null ?
                new ObjectParameter("DocLibName", docLibName) :
                new ObjectParameter("DocLibName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DupThreads_CheckDeleteThreadStatus", docLibNameParameter);
        }
    
        public virtual ObjectResult<DupThreads_FetchDocLibStatus_Result> DupThreads_FetchDocLibStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DupThreads_FetchDocLibStatus_Result>("DupThreads_FetchDocLibStatus");
        }
    
        public virtual ObjectResult<DupThreads_FetchThreadstobeDeleted_Result> DupThreads_FetchThreadstobeDeleted(string processedBy)
        {
            var processedByParameter = processedBy != null ?
                new ObjectParameter("ProcessedBy", processedBy) :
                new ObjectParameter("ProcessedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DupThreads_FetchThreadstobeDeleted_Result>("DupThreads_FetchThreadstobeDeleted", processedByParameter);
        }
    
        public virtual ObjectResult<DupThreads_FetchThreadstobeDeleted_bckp_Result> DupThreads_FetchThreadstobeDeleted_bckp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DupThreads_FetchThreadstobeDeleted_bckp_Result>("DupThreads_FetchThreadstobeDeleted_bckp");
        }
    
        public virtual ObjectResult<string> DupThreads_FetchTopLevelFolders(string docLibName)
        {
            var docLibNameParameter = docLibName != null ?
                new ObjectParameter("DocLibName", docLibName) :
                new ObjectParameter("DocLibName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("DupThreads_FetchTopLevelFolders", docLibNameParameter);
        }
    
        public virtual int DupThreads_InsertThreadInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DupThreads_InsertThreadInfo");
        }
    
        public virtual int DupThreads_InsertThreadInfo_bak()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DupThreads_InsertThreadInfo_bak");
        }
    
        public virtual int DupThreads_InsertTopLevelSubfolders(string docLibName)
        {
            var docLibNameParameter = docLibName != null ?
                new ObjectParameter("DocLibName", docLibName) :
                new ObjectParameter("DocLibName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DupThreads_InsertTopLevelSubfolders", docLibNameParameter);
        }
    
        public virtual int DupThreads_InsertTopLevelSubfolders_bak20180515(string docLibName)
        {
            var docLibNameParameter = docLibName != null ?
                new ObjectParameter("DocLibName", docLibName) :
                new ObjectParameter("DocLibName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DupThreads_InsertTopLevelSubfolders_bak20180515", docLibNameParameter);
        }
    
        public virtual int DupThreads_UpdateDeletedThreadStatus(string threadID_Filename, string threadID_Path, Nullable<long> threadID_Size, string docLibname)
        {
            var threadID_FilenameParameter = threadID_Filename != null ?
                new ObjectParameter("ThreadID_Filename", threadID_Filename) :
                new ObjectParameter("ThreadID_Filename", typeof(string));
    
            var threadID_PathParameter = threadID_Path != null ?
                new ObjectParameter("ThreadID_Path", threadID_Path) :
                new ObjectParameter("ThreadID_Path", typeof(string));
    
            var threadID_SizeParameter = threadID_Size.HasValue ?
                new ObjectParameter("ThreadID_Size", threadID_Size) :
                new ObjectParameter("ThreadID_Size", typeof(long));
    
            var docLibnameParameter = docLibname != null ?
                new ObjectParameter("DocLibname", docLibname) :
                new ObjectParameter("DocLibname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DupThreads_UpdateDeletedThreadStatus", threadID_FilenameParameter, threadID_PathParameter, threadID_SizeParameter, docLibnameParameter);
        }
    
        public virtual int DupThreads_UpdateDeletedThreadStatus_bckp(string threadID_Filename, string threadID_Path, Nullable<long> threadID_Size, string docLibname)
        {
            var threadID_FilenameParameter = threadID_Filename != null ?
                new ObjectParameter("ThreadID_Filename", threadID_Filename) :
                new ObjectParameter("ThreadID_Filename", typeof(string));
    
            var threadID_PathParameter = threadID_Path != null ?
                new ObjectParameter("ThreadID_Path", threadID_Path) :
                new ObjectParameter("ThreadID_Path", typeof(string));
    
            var threadID_SizeParameter = threadID_Size.HasValue ?
                new ObjectParameter("ThreadID_Size", threadID_Size) :
                new ObjectParameter("ThreadID_Size", typeof(long));
    
            var docLibnameParameter = docLibname != null ?
                new ObjectParameter("DocLibname", docLibname) :
                new ObjectParameter("DocLibname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DupThreads_UpdateDeletedThreadStatus_bckp", threadID_FilenameParameter, threadID_PathParameter, threadID_SizeParameter, docLibnameParameter);
        }
    
        public virtual int DupThreads_UpdateDeletedThreadStatus_bckp1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DupThreads_UpdateDeletedThreadStatus_bckp1");
        }
    
        public virtual int Yammer_BulkInsert(string filePath, string tableName)
        {
            var filePathParameter = filePath != null ?
                new ObjectParameter("FilePath", filePath) :
                new ObjectParameter("FilePath", typeof(string));
    
            var tableNameParameter = tableName != null ?
                new ObjectParameter("TableName", tableName) :
                new ObjectParameter("TableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_BulkInsert", filePathParameter, tableNameParameter);
        }
    
        public virtual ObjectResult<Yammer_CheckAnyContainerInProgress_Result> Yammer_CheckAnyContainerInProgress(Nullable<int> ymyear, string processedBy)
        {
            var ymyearParameter = ymyear.HasValue ?
                new ObjectParameter("ymyear", ymyear) :
                new ObjectParameter("ymyear", typeof(int));
    
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Yammer_CheckAnyContainerInProgress_Result>("Yammer_CheckAnyContainerInProgress", ymyearParameter, processedByParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Yammer_CheckBatchInProgress(Nullable<int> year, string processedBy)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Yammer_CheckBatchInProgress", yearParameter, processedByParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Yammer_CheckExportDetailsForSharepoint(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Yammer_CheckExportDetailsForSharepoint", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Yammer_CheckFolderExistsInContainer(Nullable<int> ymyear, string sourceFolderpath)
        {
            var ymyearParameter = ymyear.HasValue ?
                new ObjectParameter("ymyear", ymyear) :
                new ObjectParameter("ymyear", typeof(int));
    
            var sourceFolderpathParameter = sourceFolderpath != null ?
                new ObjectParameter("sourceFolderpath", sourceFolderpath) :
                new ObjectParameter("sourceFolderpath", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Yammer_CheckFolderExistsInContainer", ymyearParameter, sourceFolderpathParameter);
        }
    
        public virtual ObjectResult<Yammer_CheckRangeForFileMove_Result> Yammer_CheckRangeForFileMove(string processedBy, Nullable<int> rangeInMonths, Nullable<int> rangeInDays)
        {
            var processedByParameter = processedBy != null ?
                new ObjectParameter("ProcessedBy", processedBy) :
                new ObjectParameter("ProcessedBy", typeof(string));
    
            var rangeInMonthsParameter = rangeInMonths.HasValue ?
                new ObjectParameter("RangeInMonths", rangeInMonths) :
                new ObjectParameter("RangeInMonths", typeof(int));
    
            var rangeInDaysParameter = rangeInDays.HasValue ?
                new ObjectParameter("RangeInDays", rangeInDays) :
                new ObjectParameter("RangeInDays", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Yammer_CheckRangeForFileMove_Result>("Yammer_CheckRangeForFileMove", processedByParameter, rangeInMonthsParameter, rangeInDaysParameter);
        }
    
        public virtual int Yammer_CleanupMessageTable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_CleanupMessageTable");
        }
    
        public virtual int Yammer_Common_LogEvent(string in_nvarchar_Source, string in_nvarchar_EventType, string in_nvarchar_FileName, string in_nvarchar_ErrorDescription, string processedBy)
        {
            var in_nvarchar_SourceParameter = in_nvarchar_Source != null ?
                new ObjectParameter("in_nvarchar_Source", in_nvarchar_Source) :
                new ObjectParameter("in_nvarchar_Source", typeof(string));
    
            var in_nvarchar_EventTypeParameter = in_nvarchar_EventType != null ?
                new ObjectParameter("in_nvarchar_EventType", in_nvarchar_EventType) :
                new ObjectParameter("in_nvarchar_EventType", typeof(string));
    
            var in_nvarchar_FileNameParameter = in_nvarchar_FileName != null ?
                new ObjectParameter("in_nvarchar_FileName", in_nvarchar_FileName) :
                new ObjectParameter("in_nvarchar_FileName", typeof(string));
    
            var in_nvarchar_ErrorDescriptionParameter = in_nvarchar_ErrorDescription != null ?
                new ObjectParameter("in_nvarchar_ErrorDescription", in_nvarchar_ErrorDescription) :
                new ObjectParameter("in_nvarchar_ErrorDescription", typeof(string));
    
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_Common_LogEvent", in_nvarchar_SourceParameter, in_nvarchar_EventTypeParameter, in_nvarchar_FileNameParameter, in_nvarchar_ErrorDescriptionParameter, processedByParameter);
        }
    
        public virtual int Yammer_Common_UpdateStatus(string in_nvarchar_startDate, string in_nvarchar_endDate, string in_nvarchar_status, string in_nvarchar_stage, Nullable<int> in_int_timeTried, Nullable<bool> in_bit_toMove)
        {
            var in_nvarchar_startDateParameter = in_nvarchar_startDate != null ?
                new ObjectParameter("in_nvarchar_startDate", in_nvarchar_startDate) :
                new ObjectParameter("in_nvarchar_startDate", typeof(string));
    
            var in_nvarchar_endDateParameter = in_nvarchar_endDate != null ?
                new ObjectParameter("in_nvarchar_endDate", in_nvarchar_endDate) :
                new ObjectParameter("in_nvarchar_endDate", typeof(string));
    
            var in_nvarchar_statusParameter = in_nvarchar_status != null ?
                new ObjectParameter("in_nvarchar_status", in_nvarchar_status) :
                new ObjectParameter("in_nvarchar_status", typeof(string));
    
            var in_nvarchar_stageParameter = in_nvarchar_stage != null ?
                new ObjectParameter("in_nvarchar_stage", in_nvarchar_stage) :
                new ObjectParameter("in_nvarchar_stage", typeof(string));
    
            var in_int_timeTriedParameter = in_int_timeTried.HasValue ?
                new ObjectParameter("in_int_timeTried", in_int_timeTried) :
                new ObjectParameter("in_int_timeTried", typeof(int));
    
            var in_bit_toMoveParameter = in_bit_toMove.HasValue ?
                new ObjectParameter("in_bit_toMove", in_bit_toMove) :
                new ObjectParameter("in_bit_toMove", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_Common_UpdateStatus", in_nvarchar_startDateParameter, in_nvarchar_endDateParameter, in_nvarchar_statusParameter, in_nvarchar_stageParameter, in_int_timeTriedParameter, in_bit_toMoveParameter);
        }
    
        public virtual ObjectResult<Yammer_Compress_GetProcessingCount_Result> Yammer_Compress_GetProcessingCount(Nullable<int> year, Nullable<int> rangeInMonths, Nullable<int> rangeInDays)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var rangeInMonthsParameter = rangeInMonths.HasValue ?
                new ObjectParameter("RangeInMonths", rangeInMonths) :
                new ObjectParameter("RangeInMonths", typeof(int));
    
            var rangeInDaysParameter = rangeInDays.HasValue ?
                new ObjectParameter("RangeInDays", rangeInDays) :
                new ObjectParameter("RangeInDays", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Yammer_Compress_GetProcessingCount_Result>("Yammer_Compress_GetProcessingCount", yearParameter, rangeInMonthsParameter, rangeInDaysParameter);
        }
    
        public virtual int Yammer_ContainerMapping(string containerName, string gUID, Nullable<int> ymyear, string sPLibraryName, string status, string packageStage, string processedBy, string sourceFolderPath, Nullable<long> threadcount, string fileContainerUri, string packageContainerUri, string reportingQueueUri, Nullable<int> batchNo)
        {
            var containerNameParameter = containerName != null ?
                new ObjectParameter("ContainerName", containerName) :
                new ObjectParameter("ContainerName", typeof(string));
    
            var gUIDParameter = gUID != null ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(string));
    
            var ymyearParameter = ymyear.HasValue ?
                new ObjectParameter("ymyear", ymyear) :
                new ObjectParameter("ymyear", typeof(int));
    
            var sPLibraryNameParameter = sPLibraryName != null ?
                new ObjectParameter("SPLibraryName", sPLibraryName) :
                new ObjectParameter("SPLibraryName", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var packageStageParameter = packageStage != null ?
                new ObjectParameter("packageStage", packageStage) :
                new ObjectParameter("packageStage", typeof(string));
    
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            var sourceFolderPathParameter = sourceFolderPath != null ?
                new ObjectParameter("SourceFolderPath", sourceFolderPath) :
                new ObjectParameter("SourceFolderPath", typeof(string));
    
            var threadcountParameter = threadcount.HasValue ?
                new ObjectParameter("threadcount", threadcount) :
                new ObjectParameter("threadcount", typeof(long));
    
            var fileContainerUriParameter = fileContainerUri != null ?
                new ObjectParameter("FileContainerUri", fileContainerUri) :
                new ObjectParameter("FileContainerUri", typeof(string));
    
            var packageContainerUriParameter = packageContainerUri != null ?
                new ObjectParameter("PackageContainerUri", packageContainerUri) :
                new ObjectParameter("PackageContainerUri", typeof(string));
    
            var reportingQueueUriParameter = reportingQueueUri != null ?
                new ObjectParameter("ReportingQueueUri", reportingQueueUri) :
                new ObjectParameter("ReportingQueueUri", typeof(string));
    
            var batchNoParameter = batchNo.HasValue ?
                new ObjectParameter("BatchNo", batchNo) :
                new ObjectParameter("BatchNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_ContainerMapping", containerNameParameter, gUIDParameter, ymyearParameter, sPLibraryNameParameter, statusParameter, packageStageParameter, processedByParameter, sourceFolderPathParameter, threadcountParameter, fileContainerUriParameter, packageContainerUriParameter, reportingQueueUriParameter, batchNoParameter);
        }
    
        public virtual int Yammer_DeleteArchThread(string in_nvarchar_thread_id)
        {
            var in_nvarchar_thread_idParameter = in_nvarchar_thread_id != null ?
                new ObjectParameter("in_nvarchar_thread_id", in_nvarchar_thread_id) :
                new ObjectParameter("in_nvarchar_thread_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_DeleteArchThread", in_nvarchar_thread_idParameter);
        }
    
        public virtual int Yammer_DeleteJobIds(string jobId)
        {
            var jobIdParameter = jobId != null ?
                new ObjectParameter("jobId", jobId) :
                new ObjectParameter("jobId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_DeleteJobIds", jobIdParameter);
        }
    
        public virtual ObjectResult<string> Yammer_DocumentLibraryCreation(string ymyear, string sPLibraryName, Nullable<long> groupcount, Nullable<long> threadcount, Nullable<long> capacity, string processedBy)
        {
            var ymyearParameter = ymyear != null ?
                new ObjectParameter("ymyear", ymyear) :
                new ObjectParameter("ymyear", typeof(string));
    
            var sPLibraryNameParameter = sPLibraryName != null ?
                new ObjectParameter("SPLibraryName", sPLibraryName) :
                new ObjectParameter("SPLibraryName", typeof(string));
    
            var groupcountParameter = groupcount.HasValue ?
                new ObjectParameter("groupcount", groupcount) :
                new ObjectParameter("groupcount", typeof(long));
    
            var threadcountParameter = threadcount.HasValue ?
                new ObjectParameter("threadcount", threadcount) :
                new ObjectParameter("threadcount", typeof(long));
    
            var capacityParameter = capacity.HasValue ?
                new ObjectParameter("capacity", capacity) :
                new ObjectParameter("capacity", typeof(long));
    
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Yammer_DocumentLibraryCreation", ymyearParameter, sPLibraryNameParameter, groupcountParameter, threadcountParameter, capacityParameter, processedByParameter);
        }
    
        public virtual int Yammer_Download_DeleteExportDetails(string in_nvarchar_startDate, string in_nvarchar_endDate)
        {
            var in_nvarchar_startDateParameter = in_nvarchar_startDate != null ?
                new ObjectParameter("in_nvarchar_startDate", in_nvarchar_startDate) :
                new ObjectParameter("in_nvarchar_startDate", typeof(string));
    
            var in_nvarchar_endDateParameter = in_nvarchar_endDate != null ?
                new ObjectParameter("in_nvarchar_endDate", in_nvarchar_endDate) :
                new ObjectParameter("in_nvarchar_endDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_Download_DeleteExportDetails", in_nvarchar_startDateParameter, in_nvarchar_endDateParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Yammer_Download_GetInProgressCount(string in_varchar_year, string processedBy)
        {
            var in_varchar_yearParameter = in_varchar_year != null ?
                new ObjectParameter("in_varchar_year", in_varchar_year) :
                new ObjectParameter("in_varchar_year", typeof(string));
    
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Yammer_Download_GetInProgressCount", in_varchar_yearParameter, processedByParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> Yammer_Download_GetLastEnddate(string in_varchar_year)
        {
            var in_varchar_yearParameter = in_varchar_year != null ?
                new ObjectParameter("in_varchar_year", in_varchar_year) :
                new ObjectParameter("in_varchar_year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("Yammer_Download_GetLastEnddate", in_varchar_yearParameter);
        }
    
        public virtual ObjectResult<Yammer_Download_GetTimesTried_Result> Yammer_Download_GetTimesTried(string in_varchar_year, string processedBy)
        {
            var in_varchar_yearParameter = in_varchar_year != null ?
                new ObjectParameter("in_varchar_year", in_varchar_year) :
                new ObjectParameter("in_varchar_year", typeof(string));
    
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Yammer_Download_GetTimesTried_Result>("Yammer_Download_GetTimesTried", in_varchar_yearParameter, processedByParameter);
        }
    
        public virtual int Yammer_Download_NewExportDetails(string in_nvarchar_startDate, string in_nvarchar_endDate, string in_nvarchar_status, string processedBy)
        {
            var in_nvarchar_startDateParameter = in_nvarchar_startDate != null ?
                new ObjectParameter("in_nvarchar_startDate", in_nvarchar_startDate) :
                new ObjectParameter("in_nvarchar_startDate", typeof(string));
    
            var in_nvarchar_endDateParameter = in_nvarchar_endDate != null ?
                new ObjectParameter("in_nvarchar_endDate", in_nvarchar_endDate) :
                new ObjectParameter("in_nvarchar_endDate", typeof(string));
    
            var in_nvarchar_statusParameter = in_nvarchar_status != null ?
                new ObjectParameter("in_nvarchar_status", in_nvarchar_status) :
                new ObjectParameter("in_nvarchar_status", typeof(string));
    
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_Download_NewExportDetails", in_nvarchar_startDateParameter, in_nvarchar_endDateParameter, in_nvarchar_statusParameter, processedByParameter);
        }
    
        public virtual ObjectResult<Yammer_DownloadAttachments_Result> Yammer_DownloadAttachments(string fILTER, string processedBy)
        {
            var fILTERParameter = fILTER != null ?
                new ObjectParameter("FILTER", fILTER) :
                new ObjectParameter("FILTER", typeof(string));
    
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Yammer_DownloadAttachments_Result>("Yammer_DownloadAttachments", fILTERParameter, processedByParameter);
        }
    
        public virtual int Yammer_DownloadThreadStatus(string nEW_STATUS, string pREV_STATUS, string processedBy)
        {
            var nEW_STATUSParameter = nEW_STATUS != null ?
                new ObjectParameter("NEW_STATUS", nEW_STATUS) :
                new ObjectParameter("NEW_STATUS", typeof(string));
    
            var pREV_STATUSParameter = pREV_STATUS != null ?
                new ObjectParameter("PREV_STATUS", pREV_STATUS) :
                new ObjectParameter("PREV_STATUS", typeof(string));
    
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_DownloadThreadStatus", nEW_STATUSParameter, pREV_STATUSParameter, processedByParameter);
        }
    
        public virtual ObjectResult<Yammer_GetAttchmntDtlsForRename_Result> Yammer_GetAttchmntDtlsForRename(string filter, string processedBy)
        {
            var filterParameter = filter != null ?
                new ObjectParameter("filter", filter) :
                new ObjectParameter("filter", typeof(string));
    
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Yammer_GetAttchmntDtlsForRename_Result>("Yammer_GetAttchmntDtlsForRename", filterParameter, processedByParameter);
        }
    
        public virtual ObjectResult<Yammer_GetBatchToReSubmit_Result> Yammer_GetBatchToReSubmit(Nullable<int> ymYear, string processedBy, Nullable<int> batchCount)
        {
            var ymYearParameter = ymYear.HasValue ?
                new ObjectParameter("YmYear", ymYear) :
                new ObjectParameter("YmYear", typeof(int));
    
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            var batchCountParameter = batchCount.HasValue ?
                new ObjectParameter("batchCount", batchCount) :
                new ObjectParameter("batchCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Yammer_GetBatchToReSubmit_Result>("Yammer_GetBatchToReSubmit", ymYearParameter, processedByParameter, batchCountParameter);
        }
    
        public virtual ObjectResult<Yammer_GetBatchToSubmit_Result> Yammer_GetBatchToSubmit(Nullable<int> ymYear, string processedBy, Nullable<int> batchCount)
        {
            var ymYearParameter = ymYear.HasValue ?
                new ObjectParameter("YmYear", ymYear) :
                new ObjectParameter("YmYear", typeof(int));
    
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            var batchCountParameter = batchCount.HasValue ?
                new ObjectParameter("batchCount", batchCount) :
                new ObjectParameter("batchCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Yammer_GetBatchToSubmit_Result>("Yammer_GetBatchToSubmit", ymYearParameter, processedByParameter, batchCountParameter);
        }
    
        public virtual int Yammer_GetCopyFromArchiveRepo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_GetCopyFromArchiveRepo");
        }
    
        public virtual int Yammer_GetJobIdsToRemove()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_GetJobIdsToRemove");
        }
    
        public virtual ObjectResult<Yammer_GetListToMapNewVersionFiles_Result> Yammer_GetListToMapNewVersionFiles(string processedBy, string fILTER)
        {
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            var fILTERParameter = fILTER != null ?
                new ObjectParameter("FILTER", fILTER) :
                new ObjectParameter("FILTER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Yammer_GetListToMapNewVersionFiles_Result>("Yammer_GetListToMapNewVersionFiles", processedByParameter, fILTERParameter);
        }
    
        public virtual ObjectResult<Yammer_GetMsgDetailsForVer_Result> Yammer_GetMsgDetailsForVer(string processedBy)
        {
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Yammer_GetMsgDetailsForVer_Result>("Yammer_GetMsgDetailsForVer", processedByParameter);
        }
    
        public virtual ObjectResult<Yammer_GetMsgsAndArchThrdsByThrdId_Result> Yammer_GetMsgsAndArchThrdsByThrdId(string in_nvarchar_thread_id)
        {
            var in_nvarchar_thread_idParameter = in_nvarchar_thread_id != null ?
                new ObjectParameter("in_nvarchar_thread_id", in_nvarchar_thread_id) :
                new ObjectParameter("in_nvarchar_thread_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Yammer_GetMsgsAndArchThrdsByThrdId_Result>("Yammer_GetMsgsAndArchThrdsByThrdId", in_nvarchar_thread_idParameter);
        }
    
        public virtual ObjectResult<Yammer_GetOldSharePathList_Result> Yammer_GetOldSharePathList(Nullable<bool> isLarge, string pathType)
        {
            var isLargeParameter = isLarge.HasValue ?
                new ObjectParameter("isLarge", isLarge) :
                new ObjectParameter("isLarge", typeof(bool));
    
            var pathTypeParameter = pathType != null ?
                new ObjectParameter("PathType", pathType) :
                new ObjectParameter("PathType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Yammer_GetOldSharePathList_Result>("Yammer_GetOldSharePathList", isLargeParameter, pathTypeParameter);
        }
    
        public virtual ObjectResult<Yammer_GetSPDirectoryForUpload_Result> Yammer_GetSPDirectoryForUpload(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Yammer_GetSPDirectoryForUpload_Result>("Yammer_GetSPDirectoryForUpload", yearParameter);
        }
    
        public virtual ObjectResult<string> Yammer_GetStatusForLoadData(string in_nvarchar_tempFileDate)
        {
            var in_nvarchar_tempFileDateParameter = in_nvarchar_tempFileDate != null ?
                new ObjectParameter("in_nvarchar_tempFileDate", in_nvarchar_tempFileDate) :
                new ObjectParameter("in_nvarchar_tempFileDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Yammer_GetStatusForLoadData", in_nvarchar_tempFileDateParameter);
        }
    
        public virtual ObjectResult<Yammer_GetThrdsToGenFls_Result> Yammer_GetThrdsAndUsrsToGenFls(string processedBy)
        {
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Yammer_GetThrdsToGenFls_Result>("Yammer_GetThrdsAndUsrsToGenFls", processedByParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> Yammer_GetUserIds()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("Yammer_GetUserIds");
        }
    
        public virtual ObjectResult<Nullable<int>> Yammer_GetYearForDedup(string processedBy)
        {
            var processedByParameter = processedBy != null ?
                new ObjectParameter("ProcessedBy", processedBy) :
                new ObjectParameter("ProcessedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Yammer_GetYearForDedup", processedByParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Yammer_GetYearForSharepoint(string processedBy)
        {
            var processedByParameter = processedBy != null ?
                new ObjectParameter("ProcessedBy", processedBy) :
                new ObjectParameter("ProcessedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Yammer_GetYearForSharepoint", processedByParameter);
        }
    
        public virtual int Yammer_LoadFilesVersionList(string processedBy, string fILTER)
        {
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            var fILTERParameter = fILTER != null ?
                new ObjectParameter("FILTER", fILTER) :
                new ObjectParameter("FILTER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_LoadFilesVersionList", processedByParameter, fILTERParameter);
        }
    
        public virtual int Yammer_LoadSPBatchLists(Nullable<int> year, string processedBy, Nullable<int> parentBatchNo, Nullable<int> sPMappingId)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            var parentBatchNoParameter = parentBatchNo.HasValue ?
                new ObjectParameter("ParentBatchNo", parentBatchNo) :
                new ObjectParameter("ParentBatchNo", typeof(int));
    
            var sPMappingIdParameter = sPMappingId.HasValue ?
                new ObjectParameter("SPMappingId", sPMappingId) :
                new ObjectParameter("SPMappingId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_LoadSPBatchLists", yearParameter, processedByParameter, parentBatchNoParameter, sPMappingIdParameter);
        }
    
        public virtual int Yammer_LoadSPDirectoryMapping(string uploadStartDate, string uploadEndDate, string folderPath, Nullable<long> threadCount, string processedBy)
        {
            var uploadStartDateParameter = uploadStartDate != null ?
                new ObjectParameter("uploadStartDate", uploadStartDate) :
                new ObjectParameter("uploadStartDate", typeof(string));
    
            var uploadEndDateParameter = uploadEndDate != null ?
                new ObjectParameter("uploadEndDate", uploadEndDate) :
                new ObjectParameter("uploadEndDate", typeof(string));
    
            var folderPathParameter = folderPath != null ?
                new ObjectParameter("folderPath", folderPath) :
                new ObjectParameter("folderPath", typeof(string));
    
            var threadCountParameter = threadCount.HasValue ?
                new ObjectParameter("threadCount", threadCount) :
                new ObjectParameter("threadCount", typeof(long));
    
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_LoadSPDirectoryMapping", uploadStartDateParameter, uploadEndDateParameter, folderPathParameter, threadCountParameter, processedByParameter);
        }
    
        public virtual int Yammer_LoadUserIdFromBody(string processedBy)
        {
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_LoadUserIdFromBody", processedByParameter);
        }
    
        public virtual int Yammer_LogMissedAttachments(string attachmentType, Nullable<long> fileId, string threadId)
        {
            var attachmentTypeParameter = attachmentType != null ?
                new ObjectParameter("attachmentType", attachmentType) :
                new ObjectParameter("attachmentType", typeof(string));
    
            var fileIdParameter = fileId.HasValue ?
                new ObjectParameter("fileId", fileId) :
                new ObjectParameter("fileId", typeof(long));
    
            var threadIdParameter = threadId != null ?
                new ObjectParameter("threadId", threadId) :
                new ObjectParameter("threadId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_LogMissedAttachments", attachmentTypeParameter, fileIdParameter, threadIdParameter);
        }
    
        public virtual int Yammer_MoveArchivalToRepo(string processedBy, Nullable<int> year)
        {
            var processedByParameter = processedBy != null ?
                new ObjectParameter("ProcessedBy", processedBy) :
                new ObjectParameter("ProcessedBy", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_MoveArchivalToRepo", processedByParameter, yearParameter);
        }
    
        public virtual int Yammer_PurgeProcessedData(string processed_By)
        {
            var processed_ByParameter = processed_By != null ?
                new ObjectParameter("Processed_By", processed_By) :
                new ObjectParameter("Processed_By", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_PurgeProcessedData", processed_ByParameter);
        }
    
        public virtual int Yammer_ResetArchievedThreadStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_ResetArchievedThreadStatus");
        }
    
        public virtual ObjectResult<Nullable<int>> Yammer_ResetArchievedXML()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Yammer_ResetArchievedXML");
        }
    
        public virtual int Yammer_ToDownloadUpdate(string year)
        {
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_ToDownloadUpdate", yearParameter);
        }
    
        public virtual int Yammer_ToProcessUpdate(string year)
        {
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_ToProcessUpdate", yearParameter);
        }
    
        public virtual int Yammer_Update_CompressCompletion(string year, Nullable<bool> isRangeInDays, Nullable<int> rangeInMonths)
        {
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            var isRangeInDaysParameter = isRangeInDays.HasValue ?
                new ObjectParameter("isRangeInDays", isRangeInDays) :
                new ObjectParameter("isRangeInDays", typeof(bool));
    
            var rangeInMonthsParameter = rangeInMonths.HasValue ?
                new ObjectParameter("RangeInMonths", rangeInMonths) :
                new ObjectParameter("RangeInMonths", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_Update_CompressCompletion", yearParameter, isRangeInDaysParameter, rangeInMonthsParameter);
        }
    
        public virtual int Yammer_Update_DownloadCompletion(string year)
        {
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_Update_DownloadCompletion", yearParameter);
        }
    
        public virtual int Yammer_Update_ProcessCompletion(string year, Nullable<bool> isRangeInDays, Nullable<int> toCompress, Nullable<int> rangeInMonths)
        {
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            var isRangeInDaysParameter = isRangeInDays.HasValue ?
                new ObjectParameter("isRangeInDays", isRangeInDays) :
                new ObjectParameter("isRangeInDays", typeof(bool));
    
            var toCompressParameter = toCompress.HasValue ?
                new ObjectParameter("ToCompress", toCompress) :
                new ObjectParameter("ToCompress", typeof(int));
    
            var rangeInMonthsParameter = rangeInMonths.HasValue ?
                new ObjectParameter("RangeInMonths", rangeInMonths) :
                new ObjectParameter("RangeInMonths", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_Update_ProcessCompletion", yearParameter, isRangeInDaysParameter, toCompressParameter, rangeInMonthsParameter);
        }
    
        public virtual int Yammer_Update_ProcessCompletion_bckp_517(string year, Nullable<bool> isRangeInDays, Nullable<int> toCompress, Nullable<int> rangeInMonths)
        {
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            var isRangeInDaysParameter = isRangeInDays.HasValue ?
                new ObjectParameter("isRangeInDays", isRangeInDays) :
                new ObjectParameter("isRangeInDays", typeof(bool));
    
            var toCompressParameter = toCompress.HasValue ?
                new ObjectParameter("ToCompress", toCompress) :
                new ObjectParameter("ToCompress", typeof(int));
    
            var rangeInMonthsParameter = rangeInMonths.HasValue ?
                new ObjectParameter("RangeInMonths", rangeInMonths) :
                new ObjectParameter("RangeInMonths", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_Update_ProcessCompletion_bckp_517", yearParameter, isRangeInDaysParameter, toCompressParameter, rangeInMonthsParameter);
        }
    
        public virtual int Yammer_Update_ProcessCompletion_old(string year, Nullable<bool> isRangeInDays, Nullable<int> toCompress)
        {
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            var isRangeInDaysParameter = isRangeInDays.HasValue ?
                new ObjectParameter("isRangeInDays", isRangeInDays) :
                new ObjectParameter("isRangeInDays", typeof(bool));
    
            var toCompressParameter = toCompress.HasValue ?
                new ObjectParameter("ToCompress", toCompress) :
                new ObjectParameter("ToCompress", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_Update_ProcessCompletion_old", yearParameter, isRangeInDaysParameter, toCompressParameter);
        }
    
        public virtual int Yammer_Update_YearStatus(string year, Nullable<int> toProcess, Nullable<int> toCompress, Nullable<int> toSPUpload, Nullable<int> toDedupe)
        {
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            var toProcessParameter = toProcess.HasValue ?
                new ObjectParameter("ToProcess", toProcess) :
                new ObjectParameter("ToProcess", typeof(int));
    
            var toCompressParameter = toCompress.HasValue ?
                new ObjectParameter("ToCompress", toCompress) :
                new ObjectParameter("ToCompress", typeof(int));
    
            var toSPUploadParameter = toSPUpload.HasValue ?
                new ObjectParameter("ToSPUpload", toSPUpload) :
                new ObjectParameter("ToSPUpload", typeof(int));
    
            var toDedupeParameter = toDedupe.HasValue ?
                new ObjectParameter("ToDedupe", toDedupe) :
                new ObjectParameter("ToDedupe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_Update_YearStatus", yearParameter, toProcessParameter, toCompressParameter, toSPUploadParameter, toDedupeParameter);
        }
    
        public virtual int Yammer_UpdateBatchStatus(Nullable<int> batchNo, string status, Nullable<int> timesTried, Nullable<int> itemCount)
        {
            var batchNoParameter = batchNo.HasValue ?
                new ObjectParameter("batchNo", batchNo) :
                new ObjectParameter("batchNo", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var timesTriedParameter = timesTried.HasValue ?
                new ObjectParameter("TimesTried", timesTried) :
                new ObjectParameter("TimesTried", typeof(int));
    
            var itemCountParameter = itemCount.HasValue ?
                new ObjectParameter("ItemCount", itemCount) :
                new ObjectParameter("ItemCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_UpdateBatchStatus", batchNoParameter, statusParameter, timesTriedParameter, itemCountParameter);
        }
    
        public virtual int Yammer_UpdateExpDetailsForVer(string processedBy)
        {
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_UpdateExpDetailsForVer", processedByParameter);
        }
    
        public virtual int Yammer_UpdateExpDtlsForFailedThrd()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_UpdateExpDtlsForFailedThrd");
        }
    
        public virtual int Yammer_UpdateMsgDetailsForVer(string in_nvarchar_Thread_Id, string processedBy)
        {
            var in_nvarchar_Thread_IdParameter = in_nvarchar_Thread_Id != null ?
                new ObjectParameter("in_nvarchar_Thread_Id", in_nvarchar_Thread_Id) :
                new ObjectParameter("in_nvarchar_Thread_Id", typeof(string));
    
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_UpdateMsgDetailsForVer", in_nvarchar_Thread_IdParameter, processedByParameter);
        }
    
        public virtual int Yammer_UpdateProcessingStatus(string in_nvarchar_newStatus, string in_nvarchar_prevStatus, string processedBy)
        {
            var in_nvarchar_newStatusParameter = in_nvarchar_newStatus != null ?
                new ObjectParameter("in_nvarchar_newStatus", in_nvarchar_newStatus) :
                new ObjectParameter("in_nvarchar_newStatus", typeof(string));
    
            var in_nvarchar_prevStatusParameter = in_nvarchar_prevStatus != null ?
                new ObjectParameter("in_nvarchar_prevStatus", in_nvarchar_prevStatus) :
                new ObjectParameter("in_nvarchar_prevStatus", typeof(string));
    
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_UpdateProcessingStatus", in_nvarchar_newStatusParameter, in_nvarchar_prevStatusParameter, processedByParameter);
        }
    
        public virtual int Yammer_UpdateSharepointStatus(string jobId, string status)
        {
            var jobIdParameter = jobId != null ?
                new ObjectParameter("JobId", jobId) :
                new ObjectParameter("JobId", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_UpdateSharepointStatus", jobIdParameter, statusParameter);
        }
    
        public virtual int Yammer_UpdateSPMapping(Nullable<int> batchNo, Nullable<int> year, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string processedBy)
        {
            var batchNoParameter = batchNo.HasValue ?
                new ObjectParameter("BatchNo", batchNo) :
                new ObjectParameter("BatchNo", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_UpdateSPMapping", batchNoParameter, yearParameter, startDateParameter, endDateParameter, processedByParameter);
        }
    
        public virtual int Yammer_UpdateThreadStatus(string in_nvarchar_newStatus, string in_nvarchar_prevStatus, string processedBy)
        {
            var in_nvarchar_newStatusParameter = in_nvarchar_newStatus != null ?
                new ObjectParameter("in_nvarchar_newStatus", in_nvarchar_newStatus) :
                new ObjectParameter("in_nvarchar_newStatus", typeof(string));
    
            var in_nvarchar_prevStatusParameter = in_nvarchar_prevStatus != null ?
                new ObjectParameter("in_nvarchar_prevStatus", in_nvarchar_prevStatus) :
                new ObjectParameter("in_nvarchar_prevStatus", typeof(string));
    
            var processedByParameter = processedBy != null ?
                new ObjectParameter("processedBy", processedBy) :
                new ObjectParameter("processedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_UpdateThreadStatus", in_nvarchar_newStatusParameter, in_nvarchar_prevStatusParameter, processedByParameter);
        }
    
        public virtual int Yammer_updateThreadswithNoAttachment(string nEW_STATUS, string pREV_STATUS, string pROCESSEDBY)
        {
            var nEW_STATUSParameter = nEW_STATUS != null ?
                new ObjectParameter("NEW_STATUS", nEW_STATUS) :
                new ObjectParameter("NEW_STATUS", typeof(string));
    
            var pREV_STATUSParameter = pREV_STATUS != null ?
                new ObjectParameter("PREV_STATUS", pREV_STATUS) :
                new ObjectParameter("PREV_STATUS", typeof(string));
    
            var pROCESSEDBYParameter = pROCESSEDBY != null ?
                new ObjectParameter("PROCESSEDBY", pROCESSEDBY) :
                new ObjectParameter("PROCESSEDBY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_updateThreadswithNoAttachment", nEW_STATUSParameter, pREV_STATUSParameter, pROCESSEDBYParameter);
        }
    
        public virtual int Yammer_UpdateUserDetails(string in_nvarchar_FullName, string in_nvarchar_EmailAlias, Nullable<long> in_nvarchar_UserId)
        {
            var in_nvarchar_FullNameParameter = in_nvarchar_FullName != null ?
                new ObjectParameter("in_nvarchar_FullName", in_nvarchar_FullName) :
                new ObjectParameter("in_nvarchar_FullName", typeof(string));
    
            var in_nvarchar_EmailAliasParameter = in_nvarchar_EmailAlias != null ?
                new ObjectParameter("in_nvarchar_EmailAlias", in_nvarchar_EmailAlias) :
                new ObjectParameter("in_nvarchar_EmailAlias", typeof(string));
    
            var in_nvarchar_UserIdParameter = in_nvarchar_UserId.HasValue ?
                new ObjectParameter("in_nvarchar_UserId", in_nvarchar_UserId) :
                new ObjectParameter("in_nvarchar_UserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_UpdateUserDetails", in_nvarchar_FullNameParameter, in_nvarchar_EmailAliasParameter, in_nvarchar_UserIdParameter);
        }
    
        public virtual int Yammer_VerifyMessagesCount(string cSVFILE, Nullable<long> rowCount, Nullable<long> filesCount, Nullable<long> pagesCount, Nullable<long> groupsCount, Nullable<long> topicsCount, Nullable<long> usersCount, ObjectParameter isFailed)
        {
            var cSVFILEParameter = cSVFILE != null ?
                new ObjectParameter("CSVFILE", cSVFILE) :
                new ObjectParameter("CSVFILE", typeof(string));
    
            var rowCountParameter = rowCount.HasValue ?
                new ObjectParameter("RowCount", rowCount) :
                new ObjectParameter("RowCount", typeof(long));
    
            var filesCountParameter = filesCount.HasValue ?
                new ObjectParameter("FilesCount", filesCount) :
                new ObjectParameter("FilesCount", typeof(long));
    
            var pagesCountParameter = pagesCount.HasValue ?
                new ObjectParameter("PagesCount", pagesCount) :
                new ObjectParameter("PagesCount", typeof(long));
    
            var groupsCountParameter = groupsCount.HasValue ?
                new ObjectParameter("GroupsCount", groupsCount) :
                new ObjectParameter("GroupsCount", typeof(long));
    
            var topicsCountParameter = topicsCount.HasValue ?
                new ObjectParameter("TopicsCount", topicsCount) :
                new ObjectParameter("TopicsCount", typeof(long));
    
            var usersCountParameter = usersCount.HasValue ?
                new ObjectParameter("UsersCount", usersCount) :
                new ObjectParameter("UsersCount", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Yammer_VerifyMessagesCount", cSVFILEParameter, rowCountParameter, filesCountParameter, pagesCountParameter, groupsCountParameter, topicsCountParameter, usersCountParameter, isFailed);
        }
    
        public virtual ObjectResult<Nullable<int>> Yammer_YearCompressingRequest(string processedBy, Nullable<bool> isRangeInDays)
        {
            var processedByParameter = processedBy != null ?
                new ObjectParameter("ProcessedBy", processedBy) :
                new ObjectParameter("ProcessedBy", typeof(string));
    
            var isRangeInDaysParameter = isRangeInDays.HasValue ?
                new ObjectParameter("isRangeInDays", isRangeInDays) :
                new ObjectParameter("isRangeInDays", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Yammer_YearCompressingRequest", processedByParameter, isRangeInDaysParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Yammer_YearCompressingRequest_bckp_517(string processedBy, Nullable<bool> isRangeInDays)
        {
            var processedByParameter = processedBy != null ?
                new ObjectParameter("ProcessedBy", processedBy) :
                new ObjectParameter("ProcessedBy", typeof(string));
    
            var isRangeInDaysParameter = isRangeInDays.HasValue ?
                new ObjectParameter("isRangeInDays", isRangeInDays) :
                new ObjectParameter("isRangeInDays", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Yammer_YearCompressingRequest_bckp_517", processedByParameter, isRangeInDaysParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Yammer_YearDownloadRequest(string processedBy)
        {
            var processedByParameter = processedBy != null ?
                new ObjectParameter("ProcessedBy", processedBy) :
                new ObjectParameter("ProcessedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Yammer_YearDownloadRequest", processedByParameter);
        }
    
        public virtual ObjectResult<Yammer_YearProcessingRequest_Result> Yammer_YearProcessingRequest(string processedBy, Nullable<bool> isRangeInDays)
        {
            var processedByParameter = processedBy != null ?
                new ObjectParameter("ProcessedBy", processedBy) :
                new ObjectParameter("ProcessedBy", typeof(string));
    
            var isRangeInDaysParameter = isRangeInDays.HasValue ?
                new ObjectParameter("isRangeInDays", isRangeInDays) :
                new ObjectParameter("isRangeInDays", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Yammer_YearProcessingRequest_Result>("Yammer_YearProcessingRequest", processedByParameter, isRangeInDaysParameter);
        }
    
        public virtual ObjectResult<Yammer_YearProcessingRequest_bckp_517_Result> Yammer_YearProcessingRequest_bckp_517(string processedBy, Nullable<bool> isRangeInDays)
        {
            var processedByParameter = processedBy != null ?
                new ObjectParameter("ProcessedBy", processedBy) :
                new ObjectParameter("ProcessedBy", typeof(string));
    
            var isRangeInDaysParameter = isRangeInDays.HasValue ?
                new ObjectParameter("isRangeInDays", isRangeInDays) :
                new ObjectParameter("isRangeInDays", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Yammer_YearProcessingRequest_bckp_517_Result>("Yammer_YearProcessingRequest_bckp_517", processedByParameter, isRangeInDaysParameter);
        }
    }
}
