//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YammerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class YM_AzureContainer
    {
        public int id { get; set; }
        public Nullable<int> ymyear { get; set; }
        public string SPLibraryName { get; set; }
        public string ContainerName { get; set; }
        public string FileContainerUri { get; set; }
        public string PackageContainerUri { get; set; }
        public string ReportingQueueUri { get; set; }
        public string PackageGUID { get; set; }
        public Nullable<int> BatchNo { get; set; }
        public string JobStatus { get; set; }
        public string PackageStage { get; set; }
        public string processedBy { get; set; }
        public string sourceFolderPath { get; set; }
        public Nullable<long> threadcount { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
