//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YammerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class YM_DocumentLibraries
    {
        public int id { get; set; }
        public string yammeryear { get; set; }
        public string SPLibraryName { get; set; }
        public Nullable<long> groupcount { get; set; }
        public Nullable<long> threadcount { get; set; }
        public Nullable<long> capacity { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string processedBy { get; set; }
    }
}
