//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YammerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class YM_EventLogs_Bak
    {
        public long id { get; set; }
        public string Source { get; set; }
        public string EventType { get; set; }
        public string FileName { get; set; }
        public string ErrorDescription { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ProcessedBy { get; set; }
    }
}
