//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YammerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class YM_FileShareLists
    {
        public int ShareId { get; set; }
        public string FilePath { get; set; }
        public string SharedFilePath { get; set; }
        public string PathType { get; set; }
        public Nullable<bool> isLargePath { get; set; }
    }
}
