//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YammerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class YM_PageThreadList
    {
        public long Id { get; set; }
        public Nullable<long> VersionId { get; set; }
        public Nullable<long> PageId { get; set; }
        public string PageName { get; set; }
        public Nullable<long> ThreadId { get; set; }
        public Nullable<long> GroupId { get; set; }
        public string GroupName { get; set; }
        public string CsvFileName { get; set; }
    }
}
