//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YammerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class YM_SPDirectoryMapping
    {
        public int id { get; set; }
        public System.DateTime UploadStartDate { get; set; }
        public System.DateTime UploadEndDate { get; set; }
        public string FolderPath { get; set; }
        public int ymYear { get; set; }
        public string Status { get; set; }
        public Nullable<long> ThreadCount { get; set; }
        public string ProcessedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
